# Generated by Django 5.0.6 on 2024-07-10 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('otp_totp', '0003_add_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTOTPDevice',
            fields=[
                ('totpdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='otp_totp.totpdevice')),
            ],
            options={
                'abstract': False,
            },
            bases=('otp_totp.totpdevice',),
        ),
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('used', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to='otp_totp.totpdevice')),
            ],
        ),
    ]
