# Generated by Django 5.0.6 on 2024-07-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customtotpdevice_backupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='is_2fa_enabled'),
        ),
    ]
