# Generated by Django 5.0.7 on 2024-07-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_last_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
