# Generated by Django 5.0.7 on 2024-08-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_token_last_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='background_picture',
            field=models.CharField(blank=True, max_length=150, verbose_name='background picture'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.CharField(blank=True, max_length=150, verbose_name='profile picture'),
        ),
    ]
