# Generated by Django 5.0.6 on 2024-08-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_background_picture_customuser_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='background_picture',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='picture',
        ),
    ]
