# Generated by Django 5.0.6 on 2024-08-24 09:21

import authentication.models.utils.validate_email
import authentication.models.utils.validate_name
import authentication.models.utils.validate_username
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_customuser_background_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[authentication.models.utils.validate_email.validate_email], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[authentication.models.utils.validate_name.validate_name], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[authentication.models.utils.validate_name.validate_name], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[authentication.models.utils.validate_username.validate_username], verbose_name='username'),
        ),
    ]
