# Generated by Django 5.0.6 on 2024-09-06 08:10

import authentication.models.utils.validate_lower
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupcode',
            name='code',
            field=models.CharField(max_length=8, validators=[authentication.models.utils.validate_lower.validate_lowercase_and_digits]),
        ),
    ]
