# Generated by Django 5.0.6 on 2024-08-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prfl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_picture',
            field=models.CharField(blank=True, max_length=150, verbose_name='background picture'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.CharField(blank=True, max_length=150, verbose_name='profile picture'),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='username'),
        ),
    ]
