# Generated by Django 5.0.6 on 2024-08-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prfl', '0003_profile_address_profile_badge_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_picture',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='back pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='pic'),
        ),
    ]
