# Generated by Django 5.0.6 on 2024-09-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prfl', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total',
            field=models.IntegerField(default=10, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wins',
            field=models.IntegerField(default=50, verbose_name='wins'),
        ),
    ]
