# Generated by Django 5.0.6 on 2024-09-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prfl', '0006_alter_profile_total_alter_profile_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total',
            field=models.IntegerField(default=100, verbose_name='total'),
        ),
    ]
