# Generated by Django 5.0.6 on 2024-09-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prfl', '0008_alter_profile_total_alter_profile_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
