# Generated by Django 5.0.6 on 2024-09-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prfl', '0009_remove_profile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='to_play',
            new_name='isrouted',
        ),
    ]
