# Generated by Django 5.0.6 on 2024-09-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prfl', '0010_rename_to_play_notification_isrouted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isInviting',
            field=models.BooleanField(default=False, verbose_name='isInviting'),
        ),
    ]
