version: "3.9"

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx_service
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    networks:
      - transcendence
    restart: always

  postgres:
    image: postgres:16.3
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgres/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdatabase:/var/lib/postgresql/data/pgdata:rw
    networks:
      - transcendence
    restart: always

  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
    - "11211:11211"
    networks:
    - transcendence
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    ports:
    - "6379:6379"
    volumes:
      - redisv:/data
    restart: always

volumes:
  pgdatabase:
    driver: local
  redisv:
    driver: local

networks:
  transcendence:
    driver: bridge
