
from .signup                import SignUpView
from .token                 import TokenView
from .logout                import LogoutView
from .generatetokens        import GnrToken
from .oauthGoogle           import GoogleOAuthView
from .oauth42               import IntraOAuthView
from .tokenRefresh          import TokenRefreshView
from .checkpasswd           import VerifyPasswd
from .enable2fa             import Enable2fa
from .disable2fa            import Disable2fa
from .verifydevice          import VerifyDevice
from .verify2fa             import Verify2fa
from .backupcodes           import GenerateBackupCodes
from .changepasswd          import ChangePasswd
from .resetpasswd           import ResetPasswd
from .recoverpasswd         import RequestReset
from .deleteaccount         import DeleteAccountView
from .deleteaccountcheck    import DeleteAccountAffected