# Generated by Django 4.2.1 on 2024-08-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
