# Generated by Django 4.2.1 on 2024-08-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_playerqueue_remove_match_end_time_remove_match_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapName', models.CharField(default='default', max_length=100)),
                ('ballColor', models.CharField(default='green', max_length=100)),
                ('winningScore', models.IntegerField(default=0)),
                ('is_set', models.BooleanField(default=False)),
            ],
        ),
    ]
