# Generated by Django 4.2.1 on 2024-08-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
