# Generated by Django 5.0.6 on 2024-08-20 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_match_player1_score_match_player2_score_matchhistory'),
        ('prfl', '0003_profile_address_profile_badge_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='prfl.profile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='prfl.profile'),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='prfl.profile'),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='prfl.profile'),
        ),
        migrations.AlterField(
            model_name='playerqueue',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prfl.profile'),
        ),
    ]
