# Generated by Django 5.0.6 on 2024-08-31 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_match_player1_alter_match_player2_and_more'),
        ('prfl', '0003_profile_address_profile_badge_profile_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='ballColor',
            new_name='ballcolor',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='mapName',
            new_name='mapname',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='is_set',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='winningScore',
        ),
        migrations.AddField(
            model_name='setting',
            name='botlevel',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='setting',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='prfl.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='score',
            field=models.CharField(default='Five', max_length=100),
        ),
    ]
