# Generated by Django 5.0.6 on 2024-09-22 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_ballcolor_setting_ballcolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matchHistory', to='game.match'),
        ),
    ]
