# Generated by Django 5.0.6 on 2024-09-23 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prfl', '0011_profile_isinviting'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='alias',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments_created', to='prfl.profile'),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments_participated', to='prfl.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together={('tournament', 'user', 'alias')},
        ),
    ]
