# Generated by Django 5.0.6 on 2024-09-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_tournamentparticipant_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='description',
        ),
    ]
