# Generated by Django 5.0.6 on 2024-09-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_remove_tournament_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='TournamentMatch',
        ),
    ]
