# Generated by Django 5.0.6 on 2024-09-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_rename_match_tournamentmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='scheduled_time',
        ),
    ]
