# Generated by Django 5.0.6 on 2024-10-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_remove_tournamentmatch_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='alias',
            field=models.CharField(max_length=255),
        ),
    ]
