# Generated by Django 5.0.6 on 2024-08-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
