# Generated by Django 5.0.6 on 2024-08-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_last_message_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set(),
        ),
    ]
